### ISSUE TITLE
Update to latest open release

### ISSUE THREAD

**Issue by EliJDonahue** [ArasLabs/External-Input-Example#1]
Test and update to support Aras 11 SP12.

**Comment by sampoearas** [comment]
Verified on Aras 12.0 with proper IOM install

**Comment by EliJDonahue** [comment]
@sampoearas - For future upgrade issues, please leave the issue open until the upgrade PR is merged. You can add a comment in the issue to link the PR if you want to communicate that the issue is being addressed.
